compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.3.1.cjs

# Temporary fix for https://github.com/parcel-bundler/parcel/issues/9114
packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"