compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@farmfe/cli@*":
    dependencies:
      "@farmfe/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"

yarnPath: .yarn/releases/yarn-4.4.1.cjs
