approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@farmfe/cli@*":
    dependencies:
      "@farmfe/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"
  conventional-changelog@*:
    dependencies:
      conventional-commits-filter: "*"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
