import type { PageEvent, Reflection } from "typedoc";
import { JSX } from "typedoc";
import type { GiDocgenThemeRenderContext } from "../context.ts";
import { findOwningModule } from "../utils.ts";

/**
 * Navigation placeholder. The actual nav DOM is built client-side by gi-docgen-nav.js,
 * which reads the flat navigation.js data (generated by GiDocgenTheme.getNavigation).
 */
export const giDocgenNavigation = (_context: GiDocgenThemeRenderContext, props: PageEvent<Reflection>) => {
	const owningModule = findOwningModule(props.model);
	return JSX.createElement(
		"nav",
		{ class: "tsd-navigation gi-docgen-sidebar-section" },
		JSX.createElement("h5", { class: "gi-docgen-section-heading" }, "All Modules"),
		JSX.createElement(
			"ul",
			{
				class: "tsd-small-nested-navigation gi-docgen-module-list",
				id: "tsd-nav-container",
				"data-module": owningModule?.name ?? "",
			},
			JSX.createElement("li", null, "Loading..."),
		),
	);
};
