import type { PageEvent, Reflection } from "typedoc";
import { JSX } from "typedoc";
import type { GiDocgenThemeRenderContext } from "../context.ts";

/**
 * Walk up the parent chain to find the owning Module reflection.
 * Returns undefined for project-level pages.
 */
export function findOwningModule(reflection: Reflection) {
	let current: Reflection | undefined = reflection;
	while (current) {
		if (!current.isProject() && current.parent?.isProject()) {
			return current;
		}
		current = current.parent;
	}
	return undefined;
}

/**
 * Navigation placeholder. The actual nav DOM is built client-side by gi-docgen-nav.js,
 * which reads the flat navigation.js data (generated by GiDocgenTheme.getNavigation).
 */
export const giDocgenNavigation = (_context: GiDocgenThemeRenderContext, props: PageEvent<Reflection>) => {
	const owningModule = findOwningModule(props.model);
	return JSX.createElement(
		"nav",
		{ class: "tsd-navigation" },
		JSX.createElement(
			"ul",
			{
				class: "tsd-small-nested-navigation gi-docgen-module-list",
				id: "tsd-nav-container",
				"data-module": owningModule?.name ?? "",
			},
			JSX.createElement("li", null, "Loading..."),
		),
	);
};
