export type ConstructName =
    | 'functionName'
    | 'enumMember'
    | 'signalName'
    | 'fieldName'
    | 'constantName'
    | 'constructorPropertyName'
    | 'propertyName'
    | 'parameterName'
    | 'enumName'
    | 'importNamespaceName'
    | 'signalInterfaceName'
    | 'importName'
