// Workaround
export interface GraniteServicesSettingsSerializable_ConstructProps extends ServicesSettingsSerializable_ConstructProps {}
export interface GraniteServicesSettingsSerializable extends ServicesSettingsSerializable {}