/* eslint-disable @typescript-eslint/triple-slash-reference */
import type * as Accounts10 from "./Accounts-1.0";
import type * as AccountsService10 from "./AccountsService-1.0";
import type * as Amtk4 from "./Amtk-4";
import type * as Amtk5 from "./Amtk-5";
import type * as Anjuta30 from "./Anjuta-3.0";
import type * as Anthy9000 from "./Anthy-9000";
import type * as AppStream10 from "./AppStream-1.0";
import type * as AppStreamBuilder10 from "./AppStreamBuilder-1.0";
import type * as AppStreamGlib10 from "./AppStreamGlib-1.0";
import type * as Atk10 from "./Atk-1.0";
import type * as Atspi20 from "./Atspi-2.0";
import type * as Babl01 from "./Babl-0.1";
import type * as Bamf3 from "./Bamf-3";
import type * as Builder10 from "./Builder-1.0";
import type * as Cally10 from "./Cally-1.0";
import type * as Camel12 from "./Camel-1.2";
import type * as Caribou10 from "./Caribou-1.0";
import type * as Champlain012 from "./Champlain-0.12";
import type * as Cheese30 from "./Cheese-3.0";
import type * as Clutter10 from "./Clutter-1.0";
import type * as ClutterGdk10 from "./ClutterGdk-1.0";
import type * as ClutterGst10 from "./ClutterGst-1.0";
import type * as ClutterGst20 from "./ClutterGst-2.0";
import type * as ClutterGst30 from "./ClutterGst-3.0";
import type * as ClutterX1110 from "./ClutterX11-1.0";
import type * as Cogl10 from "./Cogl-1.0";
import type * as Cogl20 from "./Cogl-2.0";
import type * as CoglGst20 from "./CoglGst-2.0";
import type * as CoglPango10 from "./CoglPango-1.0";
import type * as CoglPango20 from "./CoglPango-2.0";
import type * as ColorHug10 from "./ColorHug-1.0";
import type * as Colorhug10 from "./Colorhug-1.0";
import type * as Colord10 from "./Colord-1.0";
import type * as ColordGtk10 from "./ColordGtk-1.0";
import type * as DBus10 from "./DBus-1.0";
import type * as DBusGLib10 from "./DBusGLib-1.0";
import type * as DMAP30 from "./DMAP-3.0";
import type * as Dazzle10 from "./Dazzle-1.0";
import type * as Dbusmenu04 from "./Dbusmenu-0.4";
import type * as DbusmenuGtk04 from "./DbusmenuGtk-0.4";
import type * as DbusmenuGtk304 from "./DbusmenuGtk3-0.4";
import type * as Dee10 from "./Dee-1.0";
import type * as Devhelp30 from "./Devhelp-3.0";
import type * as EBackend12 from "./EBackend-1.2";
import type * as EBook12 from "./EBook-1.2";
import type * as EBookContacts12 from "./EBookContacts-1.2";
import type * as ECal20 from "./ECal-2.0";
import type * as ECalendar12 from "./ECalendar-1.2";
import type * as EDataBook12 from "./EDataBook-1.2";
import type * as EDataCal20 from "./EDataCal-2.0";
import type * as EDataServer12 from "./EDataServer-1.2";
import type * as EDataServerUI12 from "./EDataServerUI-1.2";
import type * as Egg10 from "./Egg-1.0";
import type * as Eog30 from "./Eog-3.0";
import type * as Epc10 from "./Epc-1.0";
import type * as EpcUi10 from "./EpcUi-1.0";
import type * as EvinceDocument30 from "./EvinceDocument-3.0";
import type * as EvinceView30 from "./EvinceView-3.0";
import type * as Farstream01 from "./Farstream-0.1";
import type * as Farstream02 from "./Farstream-0.2";
import type * as Flatpak10 from "./Flatpak-1.0";
import type * as Folks06 from "./Folks-0.6";
import type * as Folks07 from "./Folks-0.7";
import type * as FolksDummy06 from "./FolksDummy-0.6";
import type * as FolksDummy07 from "./FolksDummy-0.7";
import type * as FolksEds06 from "./FolksEds-0.6";
import type * as FolksEds07 from "./FolksEds-0.7";
import type * as FolksLibsocialweb06 from "./FolksLibsocialweb-0.6";
import type * as FolksTelepathy06 from "./FolksTelepathy-0.6";
import type * as FolksTelepathy07 from "./FolksTelepathy-0.7";
import type * as Fwupd20 from "./Fwupd-2.0";
import type * as GCab10 from "./GCab-1.0";
import type * as GCalc1 from "./GCalc-1";
import type * as GCalc2 from "./GCalc-2";
import type * as GConf20 from "./GConf-2.0";
import type * as GData00 from "./GData-0.0";
import type * as GDesktopEnums30 from "./GDesktopEnums-3.0";
import type * as GES10 from "./GES-1.0";
import type * as GExiv2010 from "./GExiv2-0.10";
import type * as GFBGraph02 from "./GFBGraph-0.2";
import type * as GFBGraph03 from "./GFBGraph-0.3";
import type * as GIRepository20 from "./GIRepository-2.0";
import type * as GL10 from "./GL-1.0";
import type * as GLib20 from "./GLib-2.0";
import type * as GMenu30 from "./GMenu-3.0";
import type * as GMime30 from "./GMime-3.0";
import type * as GModule20 from "./GModule-2.0";
import type * as GObject20 from "./GObject-2.0";
import type * as GSSDP10 from "./GSSDP-1.0";
import type * as GSSDP12 from "./GSSDP-1.2";
import type * as GSignond10 from "./GSignond-1.0";
import type * as GSound10 from "./GSound-1.0";
import type * as GSystem10 from "./GSystem-1.0";
import type * as GTop20 from "./GTop-2.0";
import type * as GUPnP10 from "./GUPnP-1.0";
import type * as GUPnP12 from "./GUPnP-1.2";
import type * as GUPnP10 from "./GUPnP-1.0";
import type * as GUPnPAV10 from "./GUPnPAV-1.0";
import type * as GUPnPDLNA10 from "./GUPnPDLNA-1.0";
import type * as GUPnPDLNA20 from "./GUPnPDLNA-2.0";
import type * as GUPnPDLNAGst20 from "./GUPnPDLNAGst-2.0";
import type * as GUPnPIgd10 from "./GUPnPIgd-1.0";
import type * as GUdev10 from "./GUdev-1.0";
import type * as GUsb10 from "./GUsb-1.0";
import type * as GVnc10 from "./GVnc-1.0";
import type * as GVncPulse10 from "./GVncPulse-1.0";
import type * as GWeather30 from "./GWeather-3.0";
import type * as GXPS01 from "./GXPS-0.1";
import type * as Gxps10 from "./Gxps-1.0";
import type * as GXml010 from "./GXml-0.10";
import type * as GXml014 from "./GXml-0.14";
import type * as GXml016 from "./GXml-0.16";
import type * as GXml018 from "./GXml-0.18";
import type * as GXml020 from "./GXml-0.20";
import type * as GXml04 from "./GXml-0.4";
import type * as Gck1 from "./Gck-1";
import type * as Gcr3 from "./Gcr-3";
import type * as GcrUi3 from "./GcrUi-3";
import type * as Gd10 from "./Gd-1.0";
import type * as Gda50 from "./Gda-5.0";
import type * as Gda60 from "./Gda-6.0";
import type * as Gdaui50 from "./Gdaui-5.0";
import type * as Gdaui60 from "./Gdaui-6.0";
import type * as Gdk20 from "./Gdk-2.0";
import type * as Gdk30 from "./Gdk-3.0";
import type * as Gdk40 from "./Gdk-4.0";
import type * as GdkPixbuf20 from "./GdkPixbuf-2.0";
import type * as GdkPixdata20 from "./GdkPixdata-2.0";
import type * as GdkWayland40 from "./GdkWayland-4.0";
import type * as GdkX1120 from "./GdkX11-2.0";
import type * as GdkX1130 from "./GdkX11-3.0";
import type * as GdkX1140 from "./GdkX11-4.0";
import type * as Gdl3 from "./Gdl-3";
import type * as Gdm10 from "./Gdm-1.0";
import type * as Gedit30 from "./Gedit-3.0";
import type * as Gee08 from "./Gee-0.8";
import type * as Gee10 from "./Gee-1.0";
import type * as Gegl03 from "./Gegl-0.3";
import type * as Gegl04 from "./Gegl-0.4";
import type * as GeglGtk301 from "./GeglGtk3-0.1";
import type * as Geoclue20 from "./Geoclue-2.0";
import type * as GeocodeGlib10 from "./GeocodeGlib-1.0";
import type * as Gepub05 from "./Gepub-0.5";
import type * as Ggit10 from "./Ggit-1.0";
import type * as Gio20 from "./Gio-2.0";
import type * as Gitg10 from "./Gitg-1.0";
import type * as GitgExt10 from "./GitgExt-1.0";
import type * as GjsDBus10 from "./GjsDBus-1.0";
import type * as Gkbd30 from "./Gkbd-3.0";
import type * as Gladeui20 from "./Gladeui-2.0";
import type * as GnomeAutoar01 from "./GnomeAutoar-0.1";
import type * as GnomeAutoarGtk01 from "./GnomeAutoarGtk-0.1";
import type * as GnomeBluetooth10 from "./GnomeBluetooth-1.0";
import type * as GnomeDesktop30 from "./GnomeDesktop-3.0";
import type * as GnomeKeyring10 from "./GnomeKeyring-1.0";
import type * as GnomeMaps10 from "./GnomeMaps-1.0";
import type * as GoVirt10 from "./GoVirt-1.0";
import type * as Goa10 from "./Goa-1.0";
import type * as GooCanvas20 from "./GooCanvas-2.0";
import type * as GooCanvas30 from "./GooCanvas-3.0";
import type * as Gpseq10 from "./Gpseq-1.0";
import type * as Granite10 from "./Granite-1.0";
import type * as Graphene10 from "./Graphene-1.0";
import type * as Grl01 from "./Grl-0.1";
import type * as Grl02 from "./Grl-0.2";
import type * as Grl03 from "./Grl-0.3";
import type * as GrlNet01 from "./GrlNet-0.1";
import type * as GrlNet02 from "./GrlNet-0.2";
import type * as GrlNet03 from "./GrlNet-0.3";
import type * as GrlPls02 from "./GrlPls-0.2";
import type * as GrlPls03 from "./GrlPls-0.3";
import type * as Grss07 from "./Grss-0.7";
import type * as Gsf1 from "./Gsf-1";
import type * as Gsk40 from "./Gsk-4.0";
import type * as Gspell1 from "./Gspell-1";
import type * as Gst10 from "./Gst-1.0";
import type * as GstAllocators10 from "./GstAllocators-1.0";
import type * as GstApp10 from "./GstApp-1.0";
import type * as GstAudio10 from "./GstAudio-1.0";
import type * as GstBadAllocators10 from "./GstBadAllocators-1.0";
import type * as GstBadAudio10 from "./GstBadAudio-1.0";
import type * as GstBase10 from "./GstBase-1.0";
import type * as GstCheck10 from "./GstCheck-1.0";
import type * as GstCodecs10 from "./GstCodecs-1.0";
import type * as GstController10 from "./GstController-1.0";
import type * as GstFft10 from "./GstFft-1.0";
import type * as GstGL10 from "./GstGL-1.0";
import type * as GstGLEGL10 from "./GstGLEGL-1.0";
import type * as GstGLWayland10 from "./GstGLWayland-1.0";
import type * as GstGLX1110 from "./GstGLX11-1.0";
import type * as GstInsertBin10 from "./GstInsertBin-1.0";
import type * as GstMpegts10 from "./GstMpegts-1.0";
import type * as GstNet10 from "./GstNet-1.0";
import type * as GstPbutils10 from "./GstPbutils-1.0";
import type * as GstPlayer10 from "./GstPlayer-1.0";
import type * as GstRiff10 from "./GstRiff-1.0";
import type * as GstRtp10 from "./GstRtp-1.0";
import type * as GstRtsp10 from "./GstRtsp-1.0";
import type * as GstRtspServer10 from "./GstRtspServer-1.0";
import type * as GstSdp10 from "./GstSdp-1.0";
import type * as GstTag10 from "./GstTag-1.0";
import type * as GstTranscoder10 from "./GstTranscoder-1.0";
import type * as GstVideo10 from "./GstVideo-1.0";
import type * as GstVulkan10 from "./GstVulkan-1.0";
import type * as GstWebRTC10 from "./GstWebRTC-1.0";
import type * as Gtef2 from "./Gtef-2";
import type * as Gtk20 from "./Gtk-2.0";
import type * as Gtk30 from "./Gtk-3.0";
import type * as Gtk40 from "./Gtk-4.0";
import type * as GtkChamplain012 from "./GtkChamplain-0.12";
import type * as GtkClutter10 from "./GtkClutter-1.0";
import type * as GtkSource30 from "./GtkSource-3.0";
import type * as GtkSource4 from "./GtkSource-4";
import type * as GtkSource5 from "./GtkSource-5";
import type * as GtkVnc20 from "./GtkVnc-2.0";
import type * as Gucharmap290 from "./Gucharmap-2.90";
import type * as Guestfs10 from "./Guestfs-1.0";
import type * as Handy00 from "./Handy-0.0";
import type * as Handy1 from "./Handy-1";
import type * as HarfBuzz00 from "./HarfBuzz-0.0";
import type * as IAnjuta30 from "./IAnjuta-3.0";
import type * as IBus10 from "./IBus-1.0";
import type * as ICal30 from "./ICal-3.0";
import type * as ICalGLib30 from "./ICalGLib-3.0";
import type * as Ide10 from "./Ide-1.0";
import type * as JSCore30 from "./JSCore-3.0";
import type * as JavaScriptCore30 from "./JavaScriptCore-3.0";
import type * as JavaScriptCore40 from "./JavaScriptCore-4.0";
import type * as Json10 from "./Json-1.0";
import type * as Jsonrpc10 from "./Jsonrpc-1.0";
import type * as Libosinfo10 from "./Libosinfo-1.0";
import type * as LibvirtGConfig10 from "./LibvirtGConfig-1.0";
import type * as LibvirtGLib10 from "./LibvirtGLib-1.0";
import type * as LibvirtGObject10 from "./LibvirtGObject-1.0";
import type * as Manette02 from "./Manette-0.2";
import type * as Mash02 from "./Mash-0.2";
import type * as Mbim10 from "./Mbim-1.0";
import type * as MediaArt10 from "./MediaArt-1.0";
import type * as MediaArt20 from "./MediaArt-2.0";
import type * as ModemManager10 from "./ModemManager-1.0";
import type * as Mx10 from "./Mx-1.0";
import type * as Mx20 from "./Mx-2.0";
import type * as MxGtk10 from "./MxGtk-1.0";
import type * as NM10 from "./NM-1.0";
import type * as NMA10 from "./NMA-1.0";
import type * as NMClient10 from "./NMClient-1.0";
import type * as NMGtk10 from "./NMGtk-1.0";
import type * as Nautilus30 from "./Nautilus-3.0";
import type * as NetworkManager10 from "./NetworkManager-1.0";
import type * as Nice01 from "./Nice-0.1";
import type * as Notify07 from "./Notify-0.7";
import type * as OSTree10 from "./OSTree-1.0";
import type * as P11Kit10 from "./P11Kit-1.0";
import type * as PackageKitGlib10 from "./PackageKitGlib-1.0";
import type * as PackageKitPlugin10 from "./PackageKitPlugin-1.0";
import type * as PanelApplet40 from "./PanelApplet-4.0";
import type * as Pango10 from "./Pango-1.0";
import type * as PangoCairo10 from "./PangoCairo-1.0";
import type * as PangoFT210 from "./PangoFT2-1.0";
import type * as PangoFc10 from "./PangoFc-1.0";
import type * as PangoOT10 from "./PangoOT-1.0";
import type * as PangoXft10 from "./PangoXft-1.0";
import type * as Peas10 from "./Peas-1.0";
import type * as PeasGtk10 from "./PeasGtk-1.0";
import type * as Pnl10 from "./Pnl-1.0";
import type * as Polkit10 from "./Polkit-1.0";
import type * as PolkitAgent10 from "./PolkitAgent-1.0";
import type * as Poppler018 from "./Poppler-0.18";
import type * as Qmi10 from "./Qmi-1.0";
import type * as Rest07 from "./Rest-0.7";
import type * as RestExtras07 from "./RestExtras-0.7";
import type * as Retro014 from "./Retro-0.14";
import type * as Retro1 from "./Retro-1";
import type * as Rsvg20 from "./Rsvg-2.0";
import type * as RygelCore24 from "./RygelCore-2.4";
import type * as RygelCore26 from "./RygelCore-2.6";
import type * as RygelRenderer24 from "./RygelRenderer-2.4";
import type * as RygelRenderer26 from "./RygelRenderer-2.6";
import type * as RygelRendererGst26 from "./RygelRendererGst-2.6";
import type * as RygelServer24 from "./RygelServer-2.4";
import type * as RygelServer26 from "./RygelServer-2.6";
import type * as Secret1 from "./Secret-1";
import type * as SecretUnstable0 from "./SecretUnstable-0";
import type * as Shumate00 from "./Shumate-0.0";
import type * as Signon20 from "./Signon-2.0";
import type * as Snapd1 from "./Snapd-1";
import type * as Soup24 from "./Soup-2.4";
import type * as SoupGNOME24 from "./SoupGNOME-2.4";
import type * as SpiceClientGLib20 from "./SpiceClientGLib-2.0";
import type * as SpiceClientGtk30 from "./SpiceClientGtk-3.0";
import type * as Sushi10 from "./Sushi-1.0";
import type * as TelepathyFarstream06 from "./TelepathyFarstream-0.6";
import type * as TelepathyGLib012 from "./TelepathyGLib-0.12";
import type * as TelepathyLogger02 from "./TelepathyLogger-0.2";
import type * as Template10 from "./Template-1.0";
import type * as Tepl4 from "./Tepl-4";
import type * as Tepl5 from "./Tepl-5";
import type * as Tepl6 from "./Tepl-6";
import type * as TimezoneMap10 from "./TimezoneMap-1.0";
import type * as Totem10 from "./Totem-1.0";
import type * as TotemPlParser10 from "./TotemPlParser-1.0";
import type * as Tracker016 from "./Tracker-0.16";
import type * as Tracker10 from "./Tracker-1.0";
import type * as Tracker20 from "./Tracker-2.0";
import type * as Tracker30 from "./Tracker-3.0";
import type * as TrackerControl10 from "./TrackerControl-1.0";
import type * as TrackerControl20 from "./TrackerControl-2.0";
import type * as TrackerExtract016 from "./TrackerExtract-0.16";
import type * as TrackerMiner016 from "./TrackerMiner-0.16";
import type * as TrackerMiner10 from "./TrackerMiner-1.0";
import type * as TrackerMiner20 from "./TrackerMiner-2.0";
import type * as UDisks20 from "./UDisks-2.0";
import type * as UPowerGlib10 from "./UPowerGlib-1.0";
import type * as Uhm00 from "./Uhm-0.0";
import type * as Unique30 from "./Unique-3.0";
import type * as Unity60 from "./Unity-6.0";
import type * as Unity70 from "./Unity-7.0";
import type * as UnityExtras70 from "./UnityExtras-7.0";
import type * as Vda1 from "./Vda-1";
import type * as Vgda1 from "./Vgda-1";
import type * as Vgpg1 from "./Vgpg-1";
import type * as Vgsl1 from "./Vgsl-1";
import type * as Vpg1 from "./Vpg-1";
import type * as Vte291 from "./Vte-2.91";
import type * as Vulkan10 from "./Vulkan-1.0";
import type * as WebKit30 from "./WebKit-3.0";
import type * as WebKit230 from "./WebKit2-3.0";
import type * as WebKit240 from "./WebKit2-4.0";
import type * as WebKit2WebExtension30 from "./WebKit2WebExtension-3.0";
import type * as WebKit2WebExtension40 from "./WebKit2WebExtension-4.0";
import type * as Wnck30 from "./Wnck-3.0";
import type * as Xkl10 from "./Xkl-1.0";
import type * as Zeitgeist20 from "./Zeitgeist-2.0";
import type * as Zpj00 from "./Zpj-0.0";
import type * as Cairo10 from "./cairo-1.0";
import type * as Fontconfig20 from "./fontconfig-2.0";
import type * as Freetype220 from "./freetype2-2.0";
import type * as GSignon10 from "./gSignon-1.0";
import type * as Libxml220 from "./libxml2-2.0";
import type * as Win3210 from "./win32-1.0";
import type * as Xfixes40 from "./xfixes-4.0";
import type * as Xft20 from "./xft-2.0";
import type * as Xlib20 from "./xlib-2.0";
import type * as Xrandr13 from "./xrandr-1.3";

declare module 'node-gtk' {
    export function require(ns: string, ver?: string): any;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Accounts10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'AccountsService10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Amtk4', ver?: '4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Amtk5', ver?: '5'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Anjuta30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Anthy9000', ver?: '9000'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'AppStream10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'AppStreamBuilder10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'AppStreamGlib10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Atk10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Atspi20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Babl01', ver?: '0.1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Bamf3', ver?: '3'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Builder10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Cally10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Camel12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Caribou10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Champlain012', ver?: '0.12'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Cheese30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Clutter10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ClutterGdk10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ClutterGst10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ClutterGst20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ClutterGst30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ClutterX1110', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Cogl10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Cogl20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'CoglGst20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'CoglPango10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'CoglPango20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ColorHug10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Colorhug10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Colord10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ColordGtk10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'DBus10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'DBusGLib10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'DMAP30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Dazzle10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Dbusmenu04', ver?: '0.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'DbusmenuGtk04', ver?: '0.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'DbusmenuGtk304', ver?: '0.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Dee10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Devhelp30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EBackend12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EBook12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EBookContacts12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ECal20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ECalendar12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EDataBook12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EDataCal20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EDataServer12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EDataServerUI12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Egg10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Eog30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Epc10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EpcUi10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EvinceDocument30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'EvinceView30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Farstream01', ver?: '0.1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Farstream02', ver?: '0.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Flatpak10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Folks06', ver?: '0.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Folks07', ver?: '0.7'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'FolksDummy06', ver?: '0.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'FolksDummy07', ver?: '0.7'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'FolksEds06', ver?: '0.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'FolksEds07', ver?: '0.7'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'FolksLibsocialweb06', ver?: '0.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'FolksTelepathy06', ver?: '0.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'FolksTelepathy07', ver?: '0.7'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Fwupd20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GCab10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GCalc1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GCalc2', ver?: '2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GConf20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GData00', ver?: '0.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GDesktopEnums30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GES10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GExiv2010', ver?: '0.10'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GFBGraph02', ver?: '0.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GFBGraph03', ver?: '0.3'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GIRepository20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GL10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GLib20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GMenu30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GMime30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GModule20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GObject20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GSSDP10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GSSDP12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GSignond10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GSound10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GSystem10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GTop20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUPnP10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUPnP12', ver?: '1.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUPnP10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUPnPAV10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUPnPDLNA10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUPnPDLNA20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUPnPDLNAGst20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUPnPIgd10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUdev10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GUsb10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GVnc10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GVncPulse10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GWeather30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GXPS01', ver?: '0.1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gxps10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GXml010', ver?: '0.10'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GXml014', ver?: '0.14'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GXml016', ver?: '0.16'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GXml018', ver?: '0.18'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GXml020', ver?: '0.20'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GXml04', ver?: '0.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gck1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gcr3', ver?: '3'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GcrUi3', ver?: '3'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gd10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gda50', ver?: '5.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gda60', ver?: '6.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gdaui50', ver?: '5.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gdaui60', ver?: '6.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gdk20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gdk30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gdk40', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GdkPixbuf20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GdkPixdata20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GdkWayland40', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GdkX1120', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GdkX1130', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GdkX1140', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gdl3', ver?: '3'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gdm10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gedit30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gee08', ver?: '0.8'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gee10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gegl03', ver?: '0.3'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gegl04', ver?: '0.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GeglGtk301', ver?: '0.1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Geoclue20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GeocodeGlib10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gepub05', ver?: '0.5'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Ggit10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gio20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gitg10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GitgExt10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GjsDBus10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gkbd30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gladeui20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GnomeAutoar01', ver?: '0.1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GnomeAutoarGtk01', ver?: '0.1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GnomeBluetooth10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GnomeDesktop30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GnomeKeyring10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GnomeMaps10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GoVirt10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Goa10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GooCanvas20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GooCanvas30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gpseq10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Granite10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Graphene10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Grl01', ver?: '0.1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Grl02', ver?: '0.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Grl03', ver?: '0.3'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GrlNet01', ver?: '0.1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GrlNet02', ver?: '0.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GrlNet03', ver?: '0.3'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GrlPls02', ver?: '0.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GrlPls03', ver?: '0.3'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Grss07', ver?: '0.7'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gsf1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gsk40', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gspell1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gst10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstAllocators10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstApp10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstAudio10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstBadAllocators10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstBadAudio10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstBase10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstCheck10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstCodecs10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstController10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstFft10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstGL10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstGLEGL10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstGLWayland10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstGLX1110', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstInsertBin10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstMpegts10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstNet10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstPbutils10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstPlayer10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstRiff10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstRtp10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstRtsp10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstRtspServer10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstSdp10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstTag10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstTranscoder10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstVideo10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstVulkan10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GstWebRTC10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gtef2', ver?: '2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gtk20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gtk30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gtk40', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GtkChamplain012', ver?: '0.12'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GtkClutter10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GtkSource30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GtkSource4', ver?: '4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GtkSource5', ver?: '5'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GtkVnc20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Gucharmap290', ver?: '2.90'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Guestfs10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Handy00', ver?: '0.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Handy1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'HarfBuzz00', ver?: '0.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'IAnjuta30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'IBus10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ICal30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ICalGLib30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Ide10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'JSCore30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'JavaScriptCore30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'JavaScriptCore40', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Json10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Jsonrpc10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Libosinfo10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'LibvirtGConfig10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'LibvirtGLib10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'LibvirtGObject10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Manette02', ver?: '0.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Mash02', ver?: '0.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Mbim10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'MediaArt10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'MediaArt20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'ModemManager10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Mx10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Mx20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'MxGtk10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'NM10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'NMA10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'NMClient10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'NMGtk10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Nautilus30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'NetworkManager10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Nice01', ver?: '0.1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Notify07', ver?: '0.7'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'OSTree10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'P11Kit10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PackageKitGlib10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PackageKitPlugin10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PanelApplet40', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Pango10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PangoCairo10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PangoFT210', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PangoFc10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PangoOT10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PangoXft10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Peas10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PeasGtk10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Pnl10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Polkit10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'PolkitAgent10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Poppler018', ver?: '0.18'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Qmi10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Rest07', ver?: '0.7'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'RestExtras07', ver?: '0.7'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Retro014', ver?: '0.14'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Retro1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Rsvg20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'RygelCore24', ver?: '2.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'RygelCore26', ver?: '2.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'RygelRenderer24', ver?: '2.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'RygelRenderer26', ver?: '2.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'RygelRendererGst26', ver?: '2.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'RygelServer24', ver?: '2.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'RygelServer26', ver?: '2.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Secret1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'SecretUnstable0', ver?: '0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Shumate00', ver?: '0.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Signon20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Snapd1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Soup24', ver?: '2.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'SoupGNOME24', ver?: '2.4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'SpiceClientGLib20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'SpiceClientGtk30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Sushi10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TelepathyFarstream06', ver?: '0.6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TelepathyGLib012', ver?: '0.12'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TelepathyLogger02', ver?: '0.2'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Template10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Tepl4', ver?: '4'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Tepl5', ver?: '5'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Tepl6', ver?: '6'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TimezoneMap10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Totem10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TotemPlParser10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Tracker016', ver?: '0.16'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Tracker10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Tracker20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Tracker30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TrackerControl10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TrackerControl20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TrackerExtract016', ver?: '0.16'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TrackerMiner016', ver?: '0.16'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TrackerMiner10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'TrackerMiner20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'UDisks20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'UPowerGlib10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Uhm00', ver?: '0.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Unique30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Unity60', ver?: '6.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Unity70', ver?: '7.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'UnityExtras70', ver?: '7.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Vda1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Vgda1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Vgpg1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Vgsl1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Vpg1', ver?: '1'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Vte291', ver?: '2.91'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Vulkan10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'WebKit30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'WebKit230', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'WebKit240', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'WebKit2WebExtension30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'WebKit2WebExtension40', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Wnck30', ver?: '3.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Xkl10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Zeitgeist20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Zpj00', ver?: '0.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Cairo10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Fontconfig20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Freetype220', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'GSignon10', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Libxml220', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Win3210', ver?: '1.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Xfixes40', ver?: '4.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Xft20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Xlib20', ver?: '2.0'): typeof ;
        // export function require(ns: ''): typeof ;
        export function require(ns: 'Xrandr13', ver?: '1.3'): typeof ;
    export function startLoop(): void;
}
