/* eslint-disable @typescript-eslint/triple-slash-reference */
import type { Accounts as Accounts10 } from "./Accounts-1.0";
import type { AccountsService as AccountsService10 } from "./AccountsService-1.0";
import type { Adw as Adw1 } from "./Adw-1";
import type { Amtk as Amtk4 } from "./Amtk-4";
import type { Amtk as Amtk5 } from "./Amtk-5";
import type { Anjuta as Anjuta30 } from "./Anjuta-3.0";
import type { Anthy as Anthy9000 } from "./Anthy-9000";
import type { AppStream as AppStream10 } from "./AppStream-1.0";
import type { AppStreamBuilder as AppStreamBuilder10 } from "./AppStreamBuilder-1.0";
import type { AppStreamGlib as AppStreamGlib10 } from "./AppStreamGlib-1.0";
import type { Atk as Atk10 } from "./Atk-1.0";
import type { Atspi as Atspi20 } from "./Atspi-2.0";
import type { Babl as Babl01 } from "./Babl-0.1";
import type { Bamf as Bamf3 } from "./Bamf-3";
import type { Builder as Builder10 } from "./Builder-1.0";
import type { Cally as Cally10 } from "./Cally-1.0";
import type { Camel as Camel12 } from "./Camel-1.2";
import type { Caribou as Caribou10 } from "./Caribou-1.0";
import type { Champlain as Champlain012 } from "./Champlain-0.12";
import type { Cheese as Cheese30 } from "./Cheese-3.0";
import type { Clutter as Clutter10 } from "./Clutter-1.0";
import type { ClutterGdk as ClutterGdk10 } from "./ClutterGdk-1.0";
import type { ClutterGst as ClutterGst10 } from "./ClutterGst-1.0";
import type { ClutterGst as ClutterGst20 } from "./ClutterGst-2.0";
import type { ClutterGst as ClutterGst30 } from "./ClutterGst-3.0";
import type { ClutterX11 as ClutterX1110 } from "./ClutterX11-1.0";
import type { Cogl as Cogl10 } from "./Cogl-1.0";
import type { Cogl as Cogl20 } from "./Cogl-2.0";
import type { CoglGst as CoglGst20 } from "./CoglGst-2.0";
import type { CoglPango as CoglPango10 } from "./CoglPango-1.0";
import type { CoglPango as CoglPango20 } from "./CoglPango-2.0";
import type { ColorHug as ColorHug10 } from "./ColorHug-1.0";
import type { Colord as Colord10 } from "./Colord-1.0";
import type { ColordGtk as ColordGtk10 } from "./ColordGtk-1.0";
import type { DBus as DBus10 } from "./DBus-1.0";
import type { DBusGLib as DBusGLib10 } from "./DBusGLib-1.0";
import type { DMAP as DMAP30 } from "./DMAP-3.0";
import type { Dazzle as Dazzle10 } from "./Dazzle-1.0";
import type { Dbusmenu as Dbusmenu04 } from "./Dbusmenu-0.4";
import type { DbusmenuGtk as DbusmenuGtk04 } from "./DbusmenuGtk-0.4";
import type { DbusmenuGtk3 as DbusmenuGtk304 } from "./DbusmenuGtk3-0.4";
import type { Dee as Dee10 } from "./Dee-1.0";
import type { Devhelp as Devhelp30 } from "./Devhelp-3.0";
import type { EBackend as EBackend12 } from "./EBackend-1.2";
import type { EBook as EBook12 } from "./EBook-1.2";
import type { EBookContacts as EBookContacts12 } from "./EBookContacts-1.2";
import type { ECal as ECal20 } from "./ECal-2.0";
import type { ECalendar as ECalendar12 } from "./ECalendar-1.2";
import type { EDataBook as EDataBook12 } from "./EDataBook-1.2";
import type { EDataCal as EDataCal20 } from "./EDataCal-2.0";
import type { EDataServer as EDataServer12 } from "./EDataServer-1.2";
import type { EDataServerUI as EDataServerUI12 } from "./EDataServerUI-1.2";
import type { Egg as Egg10 } from "./Egg-1.0";
import type { Eog as Eog30 } from "./Eog-3.0";
import type { Epc as Epc10 } from "./Epc-1.0";
import type { EpcUi as EpcUi10 } from "./EpcUi-1.0";
import type { EvinceDocument as EvinceDocument30 } from "./EvinceDocument-3.0";
import type { EvinceView as EvinceView30 } from "./EvinceView-3.0";
import type { Farstream as Farstream01 } from "./Farstream-0.1";
import type { Farstream as Farstream02 } from "./Farstream-0.2";
import type { Flatpak as Flatpak10 } from "./Flatpak-1.0";
import type { Folks as Folks06 } from "./Folks-0.6";
import type { Folks as Folks07 } from "./Folks-0.7";
import type { FolksDummy as FolksDummy06 } from "./FolksDummy-0.6";
import type { FolksDummy as FolksDummy07 } from "./FolksDummy-0.7";
import type { FolksEds as FolksEds06 } from "./FolksEds-0.6";
import type { FolksEds as FolksEds07 } from "./FolksEds-0.7";
import type { FolksLibsocialweb as FolksLibsocialweb06 } from "./FolksLibsocialweb-0.6";
import type { FolksTelepathy as FolksTelepathy06 } from "./FolksTelepathy-0.6";
import type { FolksTelepathy as FolksTelepathy07 } from "./FolksTelepathy-0.7";
import type { Fwupd as Fwupd20 } from "./Fwupd-2.0";
import type { GCab as GCab10 } from "./GCab-1.0";
import type { GCalc as GCalc1 } from "./GCalc-1";
import type { GCalc as GCalc2 } from "./GCalc-2";
import type { GConf as GConf20 } from "./GConf-2.0";
import type { GData as GData00 } from "./GData-0.0";
import type { GDesktopEnums as GDesktopEnums30 } from "./GDesktopEnums-3.0";
import type { GES as GES10 } from "./GES-1.0";
import type { GExiv2 as GExiv2010 } from "./GExiv2-0.10";
import type { GFBGraph as GFBGraph02 } from "./GFBGraph-0.2";
import type { GFBGraph as GFBGraph03 } from "./GFBGraph-0.3";
import type { GIRepository as GIRepository20 } from "./GIRepository-2.0";
import type { GL as GL10 } from "./GL-1.0";
import type { GLib as GLib20 } from "./GLib-2.0";
import type { GMenu as GMenu30 } from "./GMenu-3.0";
import type { GMime as GMime30 } from "./GMime-3.0";
import type { GModule as GModule20 } from "./GModule-2.0";
import type { GObject as GObject20 } from "./GObject-2.0";
import type { GSSDP as GSSDP10 } from "./GSSDP-1.0";
import type { GSSDP as GSSDP12 } from "./GSSDP-1.2";
import type { GSignond as GSignond10 } from "./GSignond-1.0";
import type { GSound as GSound10 } from "./GSound-1.0";
import type { GSystem as GSystem10 } from "./GSystem-1.0";
import type { GTop as GTop20 } from "./GTop-2.0";
import type { GUPnP as GUPnP10 } from "./GUPnP-1.0";
import type { GUPnP as GUPnP12 } from "./GUPnP-1.2";
import type { GUPnPAV as GUPnPAV10 } from "./GUPnPAV-1.0";
import type { GUPnPDLNA as GUPnPDLNA10 } from "./GUPnPDLNA-1.0";
import type { GUPnPDLNA as GUPnPDLNA20 } from "./GUPnPDLNA-2.0";
import type { GUPnPDLNAGst as GUPnPDLNAGst20 } from "./GUPnPDLNAGst-2.0";
import type { GUPnPIgd as GUPnPIgd10 } from "./GUPnPIgd-1.0";
import type { GUdev as GUdev10 } from "./GUdev-1.0";
import type { GUsb as GUsb10 } from "./GUsb-1.0";
import type { GVnc as GVnc10 } from "./GVnc-1.0";
import type { GVncPulse as GVncPulse10 } from "./GVncPulse-1.0";
import type { GWeather as GWeather30 } from "./GWeather-3.0";
import type { GXPS as GXPS01 } from "./GXPS-0.1";
import type { GXml as GXml010 } from "./GXml-0.10";
import type { GXml as GXml014 } from "./GXml-0.14";
import type { GXml as GXml016 } from "./GXml-0.16";
import type { GXml as GXml018 } from "./GXml-0.18";
import type { GXml as GXml020 } from "./GXml-0.20";
import type { GXml as GXml04 } from "./GXml-0.4";
import type { Gck as Gck1 } from "./Gck-1";
import type { Gcr as Gcr3 } from "./Gcr-3";
import type { GcrUi as GcrUi3 } from "./GcrUi-3";
import type { Gd as Gd10 } from "./Gd-1.0";
import type { Gda as Gda50 } from "./Gda-5.0";
import type { Gda as Gda60 } from "./Gda-6.0";
import type { Gdaui as Gdaui50 } from "./Gdaui-5.0";
import type { Gdaui as Gdaui60 } from "./Gdaui-6.0";
import type { Gdk as Gdk20 } from "./Gdk-2.0";
import type { Gdk as Gdk30 } from "./Gdk-3.0";
import type { Gdk as Gdk40 } from "./Gdk-4.0";
import type { GdkPixbuf as GdkPixbuf20 } from "./GdkPixbuf-2.0";
import type { GdkPixdata as GdkPixdata20 } from "./GdkPixdata-2.0";
import type { GdkWayland as GdkWayland40 } from "./GdkWayland-4.0";
import type { GdkX11 as GdkX1120 } from "./GdkX11-2.0";
import type { GdkX11 as GdkX1130 } from "./GdkX11-3.0";
import type { GdkX11 as GdkX1140 } from "./GdkX11-4.0";
import type { Gdl as Gdl3 } from "./Gdl-3";
import type { Gdm as Gdm10 } from "./Gdm-1.0";
import type { Gedit as Gedit30 } from "./Gedit-3.0";
import type { Gee as Gee08 } from "./Gee-0.8";
import type { Gee as Gee10 } from "./Gee-1.0";
import type { Gegl as Gegl03 } from "./Gegl-0.3";
import type { Gegl as Gegl04 } from "./Gegl-0.4";
import type { GeglGtk3 as GeglGtk301 } from "./GeglGtk3-0.1";
import type { Geoclue as Geoclue20 } from "./Geoclue-2.0";
import type { GeocodeGlib as GeocodeGlib10 } from "./GeocodeGlib-1.0";
import type { Gepub as Gepub05 } from "./Gepub-0.5";
import type { Ggit as Ggit10 } from "./Ggit-1.0";
import type { Gio as Gio20 } from "./Gio-2.0";
import type { Gitg as Gitg10 } from "./Gitg-1.0";
import type { GitgExt as GitgExt10 } from "./GitgExt-1.0";
import type { GjsDBus as GjsDBus10 } from "./GjsDBus-1.0";
import type { Gkbd as Gkbd30 } from "./Gkbd-3.0";
import type { Gladeui as Gladeui20 } from "./Gladeui-2.0";
import type { GnomeAutoar as GnomeAutoar01 } from "./GnomeAutoar-0.1";
import type { GnomeAutoarGtk as GnomeAutoarGtk01 } from "./GnomeAutoarGtk-0.1";
import type { GnomeBluetooth as GnomeBluetooth10 } from "./GnomeBluetooth-1.0";
import type { GnomeDesktop as GnomeDesktop30 } from "./GnomeDesktop-3.0";
import type { GnomeKeyring as GnomeKeyring10 } from "./GnomeKeyring-1.0";
import type { GnomeMaps as GnomeMaps10 } from "./GnomeMaps-1.0";
import type { GoVirt as GoVirt10 } from "./GoVirt-1.0";
import type { Goa as Goa10 } from "./Goa-1.0";
import type { GooCanvas as GooCanvas20 } from "./GooCanvas-2.0";
import type { GooCanvas as GooCanvas30 } from "./GooCanvas-3.0";
import type { Gpseq as Gpseq10 } from "./Gpseq-1.0";
import type { Granite as Granite10 } from "./Granite-1.0";
import type { Graphene as Graphene10 } from "./Graphene-1.0";
import type { Grl as Grl01 } from "./Grl-0.1";
import type { Grl as Grl02 } from "./Grl-0.2";
import type { Grl as Grl03 } from "./Grl-0.3";
import type { GrlNet as GrlNet01 } from "./GrlNet-0.1";
import type { GrlNet as GrlNet02 } from "./GrlNet-0.2";
import type { GrlNet as GrlNet03 } from "./GrlNet-0.3";
import type { GrlPls as GrlPls02 } from "./GrlPls-0.2";
import type { GrlPls as GrlPls03 } from "./GrlPls-0.3";
import type { Grss as Grss07 } from "./Grss-0.7";
import type { Gsf as Gsf1 } from "./Gsf-1";
import type { Gsk as Gsk40 } from "./Gsk-4.0";
import type { Gspell as Gspell1 } from "./Gspell-1";
import type { Gst as Gst10 } from "./Gst-1.0";
import type { GstAllocators as GstAllocators10 } from "./GstAllocators-1.0";
import type { GstApp as GstApp10 } from "./GstApp-1.0";
import type { GstAudio as GstAudio10 } from "./GstAudio-1.0";
import type { GstBadAllocators as GstBadAllocators10 } from "./GstBadAllocators-1.0";
import type { GstBadAudio as GstBadAudio10 } from "./GstBadAudio-1.0";
import type { GstBase as GstBase10 } from "./GstBase-1.0";
import type { GstCheck as GstCheck10 } from "./GstCheck-1.0";
import type { GstCodecs as GstCodecs10 } from "./GstCodecs-1.0";
import type { GstController as GstController10 } from "./GstController-1.0";
import type { GstFft as GstFft10 } from "./GstFft-1.0";
import type { GstGL as GstGL10 } from "./GstGL-1.0";
import type { GstGLEGL as GstGLEGL10 } from "./GstGLEGL-1.0";
import type { GstGLWayland as GstGLWayland10 } from "./GstGLWayland-1.0";
import type { GstGLX11 as GstGLX1110 } from "./GstGLX11-1.0";
import type { GstInsertBin as GstInsertBin10 } from "./GstInsertBin-1.0";
import type { GstMpegts as GstMpegts10 } from "./GstMpegts-1.0";
import type { GstNet as GstNet10 } from "./GstNet-1.0";
import type { GstPbutils as GstPbutils10 } from "./GstPbutils-1.0";
import type { GstPlayer as GstPlayer10 } from "./GstPlayer-1.0";
import type { GstRiff as GstRiff10 } from "./GstRiff-1.0";
import type { GstRtp as GstRtp10 } from "./GstRtp-1.0";
import type { GstRtsp as GstRtsp10 } from "./GstRtsp-1.0";
import type { GstRtspServer as GstRtspServer10 } from "./GstRtspServer-1.0";
import type { GstSdp as GstSdp10 } from "./GstSdp-1.0";
import type { GstTag as GstTag10 } from "./GstTag-1.0";
import type { GstTranscoder as GstTranscoder10 } from "./GstTranscoder-1.0";
import type { GstVideo as GstVideo10 } from "./GstVideo-1.0";
import type { GstVulkan as GstVulkan10 } from "./GstVulkan-1.0";
import type { GstWebRTC as GstWebRTC10 } from "./GstWebRTC-1.0";
import type { Gtef as Gtef2 } from "./Gtef-2";
import type { Gtk as Gtk20 } from "./Gtk-2.0";
import type { Gtk as Gtk30 } from "./Gtk-3.0";
import type { Gtk as Gtk40 } from "./Gtk-4.0";
import type { GtkChamplain as GtkChamplain012 } from "./GtkChamplain-0.12";
import type { GtkClutter as GtkClutter10 } from "./GtkClutter-1.0";
import type { GtkSource as GtkSource30 } from "./GtkSource-3.0";
import type { GtkSource as GtkSource4 } from "./GtkSource-4";
import type { GtkSource as GtkSource5 } from "./GtkSource-5";
import type { GtkVnc as GtkVnc20 } from "./GtkVnc-2.0";
import type { Gucharmap as Gucharmap290 } from "./Gucharmap-2.90";
import type { Guestfs as Guestfs10 } from "./Guestfs-1.0";
import type { Gxps as Gxps10 } from "./Gxps-1.0";
import type { Handy as Handy00 } from "./Handy-0.0";
import type { Handy as Handy1 } from "./Handy-1";
import type { HarfBuzz as HarfBuzz00 } from "./HarfBuzz-0.0";
import type { IAnjuta as IAnjuta30 } from "./IAnjuta-3.0";
import type { IBus as IBus10 } from "./IBus-1.0";
import type { ICal as ICal30 } from "./ICal-3.0";
import type { ICalGLib as ICalGLib30 } from "./ICalGLib-3.0";
import type { Ide as Ide10 } from "./Ide-1.0";
import type { JSCore as JSCore30 } from "./JSCore-3.0";
import type { JavaScriptCore as JavaScriptCore30 } from "./JavaScriptCore-3.0";
import type { JavaScriptCore as JavaScriptCore40 } from "./JavaScriptCore-4.0";
import type { Json as Json10 } from "./Json-1.0";
import type { Jsonrpc as Jsonrpc10 } from "./Jsonrpc-1.0";
import type { Libosinfo as Libosinfo10 } from "./Libosinfo-1.0";
import type { LibvirtGConfig as LibvirtGConfig10 } from "./LibvirtGConfig-1.0";
import type { LibvirtGLib as LibvirtGLib10 } from "./LibvirtGLib-1.0";
import type { LibvirtGObject as LibvirtGObject10 } from "./LibvirtGObject-1.0";
import type { Manette as Manette02 } from "./Manette-0.2";
import type { Mash as Mash02 } from "./Mash-0.2";
import type { Mbim as Mbim10 } from "./Mbim-1.0";
import type { MediaArt as MediaArt10 } from "./MediaArt-1.0";
import type { MediaArt as MediaArt20 } from "./MediaArt-2.0";
import type { ModemManager as ModemManager10 } from "./ModemManager-1.0";
import type { Mx as Mx10 } from "./Mx-1.0";
import type { Mx as Mx20 } from "./Mx-2.0";
import type { MxGtk as MxGtk10 } from "./MxGtk-1.0";
import type { NM as NM10 } from "./NM-1.0";
import type { NMA as NMA10 } from "./NMA-1.0";
import type { NMClient as NMClient10 } from "./NMClient-1.0";
import type { NMGtk as NMGtk10 } from "./NMGtk-1.0";
import type { Nautilus as Nautilus30 } from "./Nautilus-3.0";
import type { NetworkManager as NetworkManager10 } from "./NetworkManager-1.0";
import type { Nice as Nice01 } from "./Nice-0.1";
import type { Notify as Notify07 } from "./Notify-0.7";
import type { OSTree as OSTree10 } from "./OSTree-1.0";
import type { P11Kit as P11Kit10 } from "./P11Kit-1.0";
import type { PackageKitGlib as PackageKitGlib10 } from "./PackageKitGlib-1.0";
import type { PackageKitPlugin as PackageKitPlugin10 } from "./PackageKitPlugin-1.0";
import type { PanelApplet as PanelApplet40 } from "./PanelApplet-4.0";
import type { Pango as Pango10 } from "./Pango-1.0";
import type { PangoCairo as PangoCairo10 } from "./PangoCairo-1.0";
import type { PangoFT2 as PangoFT210 } from "./PangoFT2-1.0";
import type { PangoFc as PangoFc10 } from "./PangoFc-1.0";
import type { PangoOT as PangoOT10 } from "./PangoOT-1.0";
import type { PangoXft as PangoXft10 } from "./PangoXft-1.0";
import type { Peas as Peas10 } from "./Peas-1.0";
import type { PeasGtk as PeasGtk10 } from "./PeasGtk-1.0";
import type { Pnl as Pnl10 } from "./Pnl-1.0";
import type { Polkit as Polkit10 } from "./Polkit-1.0";
import type { PolkitAgent as PolkitAgent10 } from "./PolkitAgent-1.0";
import type { Poppler as Poppler018 } from "./Poppler-0.18";
import type { Qmi as Qmi10 } from "./Qmi-1.0";
import type { Rest as Rest07 } from "./Rest-0.7";
import type { RestExtras as RestExtras07 } from "./RestExtras-0.7";
import type { Retro as Retro014 } from "./Retro-0.14";
import type { Retro as Retro1 } from "./Retro-1";
import type { Rsvg as Rsvg20 } from "./Rsvg-2.0";
import type { RygelCore as RygelCore24 } from "./RygelCore-2.4";
import type { RygelCore as RygelCore26 } from "./RygelCore-2.6";
import type { RygelRenderer as RygelRenderer24 } from "./RygelRenderer-2.4";
import type { RygelRenderer as RygelRenderer26 } from "./RygelRenderer-2.6";
import type { RygelRendererGst as RygelRendererGst26 } from "./RygelRendererGst-2.6";
import type { RygelServer as RygelServer24 } from "./RygelServer-2.4";
import type { RygelServer as RygelServer26 } from "./RygelServer-2.6";
import type { Secret as Secret1 } from "./Secret-1";
import type { SecretUnstable as SecretUnstable0 } from "./SecretUnstable-0";
import type { Shumate as Shumate00 } from "./Shumate-0.0";
import type { Signon as Signon20 } from "./Signon-2.0";
import type { Snapd as Snapd1 } from "./Snapd-1";
import type { Soup as Soup24 } from "./Soup-2.4";
import type { SoupGNOME as SoupGNOME24 } from "./SoupGNOME-2.4";
import type { SpiceClientGLib as SpiceClientGLib20 } from "./SpiceClientGLib-2.0";
import type { SpiceClientGtk as SpiceClientGtk30 } from "./SpiceClientGtk-3.0";
import type { Sushi as Sushi10 } from "./Sushi-1.0";
import type { TelepathyFarstream as TelepathyFarstream06 } from "./TelepathyFarstream-0.6";
import type { TelepathyGLib as TelepathyGLib012 } from "./TelepathyGLib-0.12";
import type { TelepathyLogger as TelepathyLogger02 } from "./TelepathyLogger-0.2";
import type { Template as Template10 } from "./Template-1.0";
import type { Tepl as Tepl4 } from "./Tepl-4";
import type { Tepl as Tepl5 } from "./Tepl-5";
import type { Tepl as Tepl6 } from "./Tepl-6";
import type { TimezoneMap as TimezoneMap10 } from "./TimezoneMap-1.0";
import type { Totem as Totem10 } from "./Totem-1.0";
import type { TotemPlParser as TotemPlParser10 } from "./TotemPlParser-1.0";
import type { Tracker as Tracker016 } from "./Tracker-0.16";
import type { Tracker as Tracker10 } from "./Tracker-1.0";
import type { Tracker as Tracker20 } from "./Tracker-2.0";
import type { Tracker as Tracker30 } from "./Tracker-3.0";
import type { TrackerControl as TrackerControl10 } from "./TrackerControl-1.0";
import type { TrackerControl as TrackerControl20 } from "./TrackerControl-2.0";
import type { TrackerExtract as TrackerExtract016 } from "./TrackerExtract-0.16";
import type { TrackerMiner as TrackerMiner016 } from "./TrackerMiner-0.16";
import type { TrackerMiner as TrackerMiner10 } from "./TrackerMiner-1.0";
import type { TrackerMiner as TrackerMiner20 } from "./TrackerMiner-2.0";
import type { UDisks as UDisks20 } from "./UDisks-2.0";
import type { UPowerGlib as UPowerGlib10 } from "./UPowerGlib-1.0";
import type { Uhm as Uhm00 } from "./Uhm-0.0";
import type { Unique as Unique30 } from "./Unique-3.0";
import type { Unity as Unity60 } from "./Unity-6.0";
import type { Unity as Unity70 } from "./Unity-7.0";
import type { UnityExtras as UnityExtras70 } from "./UnityExtras-7.0";
import type { Vda as Vda1 } from "./Vda-1";
import type { Vgda as Vgda1 } from "./Vgda-1";
import type { Vgpg as Vgpg1 } from "./Vgpg-1";
import type { Vgsl as Vgsl1 } from "./Vgsl-1";
import type { Vpg as Vpg1 } from "./Vpg-1";
import type { Vte as Vte291 } from "./Vte-2.91";
import type { Vulkan as Vulkan10 } from "./Vulkan-1.0";
import type { WebKit as WebKit30 } from "./WebKit-3.0";
import type { WebKit2 as WebKit230 } from "./WebKit2-3.0";
import type { WebKit2 as WebKit240 } from "./WebKit2-4.0";
import type { WebKit2WebExtension as WebKit2WebExtension30 } from "./WebKit2WebExtension-3.0";
import type { WebKit2WebExtension as WebKit2WebExtension40 } from "./WebKit2WebExtension-4.0";
import type { Wnck as Wnck30 } from "./Wnck-3.0";
import type { Xkl as Xkl10 } from "./Xkl-1.0";
import type { Zeitgeist as Zeitgeist20 } from "./Zeitgeist-2.0";
import type { Zpj as Zpj00 } from "./Zpj-0.0";
import type { cairo as Cairo10 } from "./cairo-1.0";
import type { fontconfig as Fontconfig20 } from "./fontconfig-2.0";
import type { freetype2 as Freetype220 } from "./freetype2-2.0";
import type { gSignon as GSignon10 } from "./gSignon-1.0";
import type { libxml2 as Libxml220 } from "./libxml2-2.0";
import type { win32 as Win3210 } from "./win32-1.0";
import type { xfixes as Xfixes40 } from "./xfixes-4.0";
import type { xft as Xft20 } from "./xft-2.0";
import type { xlib as Xlib20 } from "./xlib-2.0";
import type { xrandr as Xrandr13 } from "./xrandr-1.3";
import type { Gst as Gst010 } from "./Gst-0.10";
import type { GstBase as GstBase010 } from "./GstBase-0.10";
import type { GstInterfaces as GstInterfaces010 } from "./GstInterfaces-0.10";
import type { GstPbutils as GstPbutils010 } from "./GstPbutils-0.10";
import type { GstTag as GstTag010 } from "./GstTag-0.10";
import type { GstVideo as GstVideo010 } from "./GstVideo-0.10";
import type { SocialWebClient as SocialWebClient025 } from "./SocialWebClient-0.25";

declare module 'node-gtk' {
    export function require(ns: string, ver?: string): any;
        export function require(ns: 'Accounts', ver: '1.0'): typeof Accounts10;
        export function require(ns: 'AccountsService', ver: '1.0'): typeof AccountsService10;
        export function require(ns: 'Adw', ver: '1'): typeof Adw1;
        export function require(ns: 'Amtk', ver: '4'): typeof Amtk4;
        export function require(ns: 'Amtk', ver: '5'): typeof Amtk5;
        export function require(ns: 'Anjuta', ver: '3.0'): typeof Anjuta30;
        export function require(ns: 'Anthy', ver: '9000'): typeof Anthy9000;
        export function require(ns: 'AppStream', ver: '1.0'): typeof AppStream10;
        export function require(ns: 'AppStreamBuilder', ver: '1.0'): typeof AppStreamBuilder10;
        export function require(ns: 'AppStreamGlib', ver: '1.0'): typeof AppStreamGlib10;
        export function require(ns: 'Atk', ver: '1.0'): typeof Atk10;
        export function require(ns: 'Atspi', ver: '2.0'): typeof Atspi20;
        export function require(ns: 'Babl', ver: '0.1'): typeof Babl01;
        export function require(ns: 'Bamf', ver: '3'): typeof Bamf3;
        export function require(ns: 'Builder', ver: '1.0'): typeof Builder10;
        export function require(ns: 'Cally', ver: '1.0'): typeof Cally10;
        export function require(ns: 'Camel', ver: '1.2'): typeof Camel12;
        export function require(ns: 'Caribou', ver: '1.0'): typeof Caribou10;
        export function require(ns: 'Champlain', ver: '0.12'): typeof Champlain012;
        export function require(ns: 'Cheese', ver: '3.0'): typeof Cheese30;
        export function require(ns: 'Clutter', ver: '1.0'): typeof Clutter10;
        export function require(ns: 'ClutterGdk', ver: '1.0'): typeof ClutterGdk10;
        export function require(ns: 'ClutterGst', ver: '1.0'): typeof ClutterGst10;
        export function require(ns: 'ClutterGst', ver: '2.0'): typeof ClutterGst20;
        export function require(ns: 'ClutterGst', ver: '3.0'): typeof ClutterGst30;
        export function require(ns: 'ClutterX11', ver: '1.0'): typeof ClutterX1110;
        export function require(ns: 'Cogl', ver: '1.0'): typeof Cogl10;
        export function require(ns: 'Cogl', ver: '2.0'): typeof Cogl20;
        export function require(ns: 'CoglGst', ver: '2.0'): typeof CoglGst20;
        export function require(ns: 'CoglPango', ver: '1.0'): typeof CoglPango10;
        export function require(ns: 'CoglPango', ver: '2.0'): typeof CoglPango20;
        export function require(ns: 'ColorHug', ver: '1.0'): typeof ColorHug10;
        export function require(ns: 'Colord', ver: '1.0'): typeof Colord10;
        export function require(ns: 'ColordGtk', ver: '1.0'): typeof ColordGtk10;
        export function require(ns: 'DBus', ver: '1.0'): typeof DBus10;
        export function require(ns: 'DBusGLib', ver: '1.0'): typeof DBusGLib10;
        export function require(ns: 'DMAP', ver: '3.0'): typeof DMAP30;
        export function require(ns: 'Dazzle', ver: '1.0'): typeof Dazzle10;
        export function require(ns: 'Dbusmenu', ver: '0.4'): typeof Dbusmenu04;
        export function require(ns: 'DbusmenuGtk', ver: '0.4'): typeof DbusmenuGtk04;
        export function require(ns: 'DbusmenuGtk3', ver: '0.4'): typeof DbusmenuGtk304;
        export function require(ns: 'Dee', ver: '1.0'): typeof Dee10;
        export function require(ns: 'Devhelp', ver: '3.0'): typeof Devhelp30;
        export function require(ns: 'EBackend', ver: '1.2'): typeof EBackend12;
        export function require(ns: 'EBook', ver: '1.2'): typeof EBook12;
        export function require(ns: 'EBookContacts', ver: '1.2'): typeof EBookContacts12;
        export function require(ns: 'ECal', ver: '2.0'): typeof ECal20;
        export function require(ns: 'ECalendar', ver: '1.2'): typeof ECalendar12;
        export function require(ns: 'EDataBook', ver: '1.2'): typeof EDataBook12;
        export function require(ns: 'EDataCal', ver: '2.0'): typeof EDataCal20;
        export function require(ns: 'EDataServer', ver: '1.2'): typeof EDataServer12;
        export function require(ns: 'EDataServerUI', ver: '1.2'): typeof EDataServerUI12;
        export function require(ns: 'Egg', ver: '1.0'): typeof Egg10;
        export function require(ns: 'Eog', ver: '3.0'): typeof Eog30;
        export function require(ns: 'Epc', ver: '1.0'): typeof Epc10;
        export function require(ns: 'EpcUi', ver: '1.0'): typeof EpcUi10;
        export function require(ns: 'EvinceDocument', ver: '3.0'): typeof EvinceDocument30;
        export function require(ns: 'EvinceView', ver: '3.0'): typeof EvinceView30;
        export function require(ns: 'Farstream', ver: '0.1'): typeof Farstream01;
        export function require(ns: 'Farstream', ver: '0.2'): typeof Farstream02;
        export function require(ns: 'Flatpak', ver: '1.0'): typeof Flatpak10;
        export function require(ns: 'Folks', ver: '0.6'): typeof Folks06;
        export function require(ns: 'Folks', ver: '0.7'): typeof Folks07;
        export function require(ns: 'FolksDummy', ver: '0.6'): typeof FolksDummy06;
        export function require(ns: 'FolksDummy', ver: '0.7'): typeof FolksDummy07;
        export function require(ns: 'FolksEds', ver: '0.6'): typeof FolksEds06;
        export function require(ns: 'FolksEds', ver: '0.7'): typeof FolksEds07;
        export function require(ns: 'FolksLibsocialweb', ver: '0.6'): typeof FolksLibsocialweb06;
        export function require(ns: 'FolksTelepathy', ver: '0.6'): typeof FolksTelepathy06;
        export function require(ns: 'FolksTelepathy', ver: '0.7'): typeof FolksTelepathy07;
        export function require(ns: 'Fwupd', ver: '2.0'): typeof Fwupd20;
        export function require(ns: 'GCab', ver: '1.0'): typeof GCab10;
        export function require(ns: 'GCalc', ver: '1'): typeof GCalc1;
        export function require(ns: 'GCalc', ver: '2'): typeof GCalc2;
        export function require(ns: 'GConf', ver: '2.0'): typeof GConf20;
        export function require(ns: 'GData', ver: '0.0'): typeof GData00;
        export function require(ns: 'GDesktopEnums', ver: '3.0'): typeof GDesktopEnums30;
        export function require(ns: 'GES', ver: '1.0'): typeof GES10;
        export function require(ns: 'GExiv2', ver: '0.10'): typeof GExiv2010;
        export function require(ns: 'GFBGraph', ver: '0.2'): typeof GFBGraph02;
        export function require(ns: 'GFBGraph', ver: '0.3'): typeof GFBGraph03;
        export function require(ns: 'GIRepository', ver: '2.0'): typeof GIRepository20;
        export function require(ns: 'GL', ver: '1.0'): typeof GL10;
        export function require(ns: 'GLib', ver: '2.0'): typeof GLib20;
        export function require(ns: 'GMenu', ver: '3.0'): typeof GMenu30;
        export function require(ns: 'GMime', ver: '3.0'): typeof GMime30;
        export function require(ns: 'GModule', ver: '2.0'): typeof GModule20;
        export function require(ns: 'GObject', ver: '2.0'): typeof GObject20;
        export function require(ns: 'GSSDP', ver: '1.0'): typeof GSSDP10;
        export function require(ns: 'GSSDP', ver: '1.2'): typeof GSSDP12;
        export function require(ns: 'GSignond', ver: '1.0'): typeof GSignond10;
        export function require(ns: 'GSound', ver: '1.0'): typeof GSound10;
        export function require(ns: 'GSystem', ver: '1.0'): typeof GSystem10;
        export function require(ns: 'GTop', ver: '2.0'): typeof GTop20;
        export function require(ns: 'GUPnP', ver: '1.0'): typeof GUPnP10;
        export function require(ns: 'GUPnP', ver: '1.2'): typeof GUPnP12;
        export function require(ns: 'GUPnPAV', ver: '1.0'): typeof GUPnPAV10;
        export function require(ns: 'GUPnPDLNA', ver: '1.0'): typeof GUPnPDLNA10;
        export function require(ns: 'GUPnPDLNA', ver: '2.0'): typeof GUPnPDLNA20;
        export function require(ns: 'GUPnPDLNAGst', ver: '2.0'): typeof GUPnPDLNAGst20;
        export function require(ns: 'GUPnPIgd', ver: '1.0'): typeof GUPnPIgd10;
        export function require(ns: 'GUdev', ver: '1.0'): typeof GUdev10;
        export function require(ns: 'GUsb', ver: '1.0'): typeof GUsb10;
        export function require(ns: 'GVnc', ver: '1.0'): typeof GVnc10;
        export function require(ns: 'GVncPulse', ver: '1.0'): typeof GVncPulse10;
        export function require(ns: 'GWeather', ver: '3.0'): typeof GWeather30;
        export function require(ns: 'GXPS', ver: '0.1'): typeof GXPS01;
        export function require(ns: 'GXml', ver: '0.10'): typeof GXml010;
        export function require(ns: 'GXml', ver: '0.14'): typeof GXml014;
        export function require(ns: 'GXml', ver: '0.16'): typeof GXml016;
        export function require(ns: 'GXml', ver: '0.18'): typeof GXml018;
        export function require(ns: 'GXml', ver: '0.20'): typeof GXml020;
        export function require(ns: 'GXml', ver: '0.4'): typeof GXml04;
        export function require(ns: 'Gck', ver: '1'): typeof Gck1;
        export function require(ns: 'Gcr', ver: '3'): typeof Gcr3;
        export function require(ns: 'GcrUi', ver: '3'): typeof GcrUi3;
        export function require(ns: 'Gd', ver: '1.0'): typeof Gd10;
        export function require(ns: 'Gda', ver: '5.0'): typeof Gda50;
        export function require(ns: 'Gda', ver: '6.0'): typeof Gda60;
        export function require(ns: 'Gdaui', ver: '5.0'): typeof Gdaui50;
        export function require(ns: 'Gdaui', ver: '6.0'): typeof Gdaui60;
        export function require(ns: 'Gdk', ver: '2.0'): typeof Gdk20;
        export function require(ns: 'Gdk', ver: '3.0'): typeof Gdk30;
        export function require(ns: 'Gdk', ver: '4.0'): typeof Gdk40;
        export function require(ns: 'GdkPixbuf', ver: '2.0'): typeof GdkPixbuf20;
        export function require(ns: 'GdkPixdata', ver: '2.0'): typeof GdkPixdata20;
        export function require(ns: 'GdkWayland', ver: '4.0'): typeof GdkWayland40;
        export function require(ns: 'GdkX11', ver: '2.0'): typeof GdkX1120;
        export function require(ns: 'GdkX11', ver: '3.0'): typeof GdkX1130;
        export function require(ns: 'GdkX11', ver: '4.0'): typeof GdkX1140;
        export function require(ns: 'Gdl', ver: '3'): typeof Gdl3;
        export function require(ns: 'Gdm', ver: '1.0'): typeof Gdm10;
        export function require(ns: 'Gedit', ver: '3.0'): typeof Gedit30;
        export function require(ns: 'Gee', ver: '0.8'): typeof Gee08;
        export function require(ns: 'Gee', ver: '1.0'): typeof Gee10;
        export function require(ns: 'Gegl', ver: '0.3'): typeof Gegl03;
        export function require(ns: 'Gegl', ver: '0.4'): typeof Gegl04;
        export function require(ns: 'GeglGtk3', ver: '0.1'): typeof GeglGtk301;
        export function require(ns: 'Geoclue', ver: '2.0'): typeof Geoclue20;
        export function require(ns: 'GeocodeGlib', ver: '1.0'): typeof GeocodeGlib10;
        export function require(ns: 'Gepub', ver: '0.5'): typeof Gepub05;
        export function require(ns: 'Ggit', ver: '1.0'): typeof Ggit10;
        export function require(ns: 'Gio', ver: '2.0'): typeof Gio20;
        export function require(ns: 'Gitg', ver: '1.0'): typeof Gitg10;
        export function require(ns: 'GitgExt', ver: '1.0'): typeof GitgExt10;
        export function require(ns: 'GjsDBus', ver: '1.0'): typeof GjsDBus10;
        export function require(ns: 'Gkbd', ver: '3.0'): typeof Gkbd30;
        export function require(ns: 'Gladeui', ver: '2.0'): typeof Gladeui20;
        export function require(ns: 'GnomeAutoar', ver: '0.1'): typeof GnomeAutoar01;
        export function require(ns: 'GnomeAutoarGtk', ver: '0.1'): typeof GnomeAutoarGtk01;
        export function require(ns: 'GnomeBluetooth', ver: '1.0'): typeof GnomeBluetooth10;
        export function require(ns: 'GnomeDesktop', ver: '3.0'): typeof GnomeDesktop30;
        export function require(ns: 'GnomeKeyring', ver: '1.0'): typeof GnomeKeyring10;
        export function require(ns: 'GnomeMaps', ver: '1.0'): typeof GnomeMaps10;
        export function require(ns: 'GoVirt', ver: '1.0'): typeof GoVirt10;
        export function require(ns: 'Goa', ver: '1.0'): typeof Goa10;
        export function require(ns: 'GooCanvas', ver: '2.0'): typeof GooCanvas20;
        export function require(ns: 'GooCanvas', ver: '3.0'): typeof GooCanvas30;
        export function require(ns: 'Gpseq', ver: '1.0'): typeof Gpseq10;
        export function require(ns: 'Granite', ver: '1.0'): typeof Granite10;
        export function require(ns: 'Graphene', ver: '1.0'): typeof Graphene10;
        export function require(ns: 'Grl', ver: '0.1'): typeof Grl01;
        export function require(ns: 'Grl', ver: '0.2'): typeof Grl02;
        export function require(ns: 'Grl', ver: '0.3'): typeof Grl03;
        export function require(ns: 'GrlNet', ver: '0.1'): typeof GrlNet01;
        export function require(ns: 'GrlNet', ver: '0.2'): typeof GrlNet02;
        export function require(ns: 'GrlNet', ver: '0.3'): typeof GrlNet03;
        export function require(ns: 'GrlPls', ver: '0.2'): typeof GrlPls02;
        export function require(ns: 'GrlPls', ver: '0.3'): typeof GrlPls03;
        export function require(ns: 'Grss', ver: '0.7'): typeof Grss07;
        export function require(ns: 'Gsf', ver: '1'): typeof Gsf1;
        export function require(ns: 'Gsk', ver: '4.0'): typeof Gsk40;
        export function require(ns: 'Gspell', ver: '1'): typeof Gspell1;
        export function require(ns: 'Gst', ver: '1.0'): typeof Gst10;
        export function require(ns: 'GstAllocators', ver: '1.0'): typeof GstAllocators10;
        export function require(ns: 'GstApp', ver: '1.0'): typeof GstApp10;
        export function require(ns: 'GstAudio', ver: '1.0'): typeof GstAudio10;
        export function require(ns: 'GstBadAllocators', ver: '1.0'): typeof GstBadAllocators10;
        export function require(ns: 'GstBadAudio', ver: '1.0'): typeof GstBadAudio10;
        export function require(ns: 'GstBase', ver: '1.0'): typeof GstBase10;
        export function require(ns: 'GstCheck', ver: '1.0'): typeof GstCheck10;
        export function require(ns: 'GstCodecs', ver: '1.0'): typeof GstCodecs10;
        export function require(ns: 'GstController', ver: '1.0'): typeof GstController10;
        export function require(ns: 'GstFft', ver: '1.0'): typeof GstFft10;
        export function require(ns: 'GstGL', ver: '1.0'): typeof GstGL10;
        export function require(ns: 'GstGLEGL', ver: '1.0'): typeof GstGLEGL10;
        export function require(ns: 'GstGLWayland', ver: '1.0'): typeof GstGLWayland10;
        export function require(ns: 'GstGLX11', ver: '1.0'): typeof GstGLX1110;
        export function require(ns: 'GstInsertBin', ver: '1.0'): typeof GstInsertBin10;
        export function require(ns: 'GstMpegts', ver: '1.0'): typeof GstMpegts10;
        export function require(ns: 'GstNet', ver: '1.0'): typeof GstNet10;
        export function require(ns: 'GstPbutils', ver: '1.0'): typeof GstPbutils10;
        export function require(ns: 'GstPlayer', ver: '1.0'): typeof GstPlayer10;
        export function require(ns: 'GstRiff', ver: '1.0'): typeof GstRiff10;
        export function require(ns: 'GstRtp', ver: '1.0'): typeof GstRtp10;
        export function require(ns: 'GstRtsp', ver: '1.0'): typeof GstRtsp10;
        export function require(ns: 'GstRtspServer', ver: '1.0'): typeof GstRtspServer10;
        export function require(ns: 'GstSdp', ver: '1.0'): typeof GstSdp10;
        export function require(ns: 'GstTag', ver: '1.0'): typeof GstTag10;
        export function require(ns: 'GstTranscoder', ver: '1.0'): typeof GstTranscoder10;
        export function require(ns: 'GstVideo', ver: '1.0'): typeof GstVideo10;
        export function require(ns: 'GstVulkan', ver: '1.0'): typeof GstVulkan10;
        export function require(ns: 'GstWebRTC', ver: '1.0'): typeof GstWebRTC10;
        export function require(ns: 'Gtef', ver: '2'): typeof Gtef2;
        export function require(ns: 'Gtk', ver: '2.0'): typeof Gtk20;
        export function require(ns: 'Gtk', ver: '3.0'): typeof Gtk30;
        export function require(ns: 'Gtk', ver: '4.0'): typeof Gtk40;
        export function require(ns: 'GtkChamplain', ver: '0.12'): typeof GtkChamplain012;
        export function require(ns: 'GtkClutter', ver: '1.0'): typeof GtkClutter10;
        export function require(ns: 'GtkSource', ver: '3.0'): typeof GtkSource30;
        export function require(ns: 'GtkSource', ver: '4'): typeof GtkSource4;
        export function require(ns: 'GtkSource', ver: '5'): typeof GtkSource5;
        export function require(ns: 'GtkVnc', ver: '2.0'): typeof GtkVnc20;
        export function require(ns: 'Gucharmap', ver: '2.90'): typeof Gucharmap290;
        export function require(ns: 'Guestfs', ver: '1.0'): typeof Guestfs10;
        export function require(ns: 'Gxps', ver: '1.0'): typeof Gxps10;
        export function require(ns: 'Handy', ver: '0.0'): typeof Handy00;
        export function require(ns: 'Handy', ver: '1'): typeof Handy1;
        export function require(ns: 'HarfBuzz', ver: '0.0'): typeof HarfBuzz00;
        export function require(ns: 'IAnjuta', ver: '3.0'): typeof IAnjuta30;
        export function require(ns: 'IBus', ver: '1.0'): typeof IBus10;
        export function require(ns: 'ICal', ver: '3.0'): typeof ICal30;
        export function require(ns: 'ICalGLib', ver: '3.0'): typeof ICalGLib30;
        export function require(ns: 'Ide', ver: '1.0'): typeof Ide10;
        export function require(ns: 'JSCore', ver: '3.0'): typeof JSCore30;
        export function require(ns: 'JavaScriptCore', ver: '3.0'): typeof JavaScriptCore30;
        export function require(ns: 'JavaScriptCore', ver: '4.0'): typeof JavaScriptCore40;
        export function require(ns: 'Json', ver: '1.0'): typeof Json10;
        export function require(ns: 'Jsonrpc', ver: '1.0'): typeof Jsonrpc10;
        export function require(ns: 'Libosinfo', ver: '1.0'): typeof Libosinfo10;
        export function require(ns: 'LibvirtGConfig', ver: '1.0'): typeof LibvirtGConfig10;
        export function require(ns: 'LibvirtGLib', ver: '1.0'): typeof LibvirtGLib10;
        export function require(ns: 'LibvirtGObject', ver: '1.0'): typeof LibvirtGObject10;
        export function require(ns: 'Manette', ver: '0.2'): typeof Manette02;
        export function require(ns: 'Mash', ver: '0.2'): typeof Mash02;
        export function require(ns: 'Mbim', ver: '1.0'): typeof Mbim10;
        export function require(ns: 'MediaArt', ver: '1.0'): typeof MediaArt10;
        export function require(ns: 'MediaArt', ver: '2.0'): typeof MediaArt20;
        export function require(ns: 'ModemManager', ver: '1.0'): typeof ModemManager10;
        export function require(ns: 'Mx', ver: '1.0'): typeof Mx10;
        export function require(ns: 'Mx', ver: '2.0'): typeof Mx20;
        export function require(ns: 'MxGtk', ver: '1.0'): typeof MxGtk10;
        export function require(ns: 'NM', ver: '1.0'): typeof NM10;
        export function require(ns: 'NMA', ver: '1.0'): typeof NMA10;
        export function require(ns: 'NMClient', ver: '1.0'): typeof NMClient10;
        export function require(ns: 'NMGtk', ver: '1.0'): typeof NMGtk10;
        export function require(ns: 'Nautilus', ver: '3.0'): typeof Nautilus30;
        export function require(ns: 'NetworkManager', ver: '1.0'): typeof NetworkManager10;
        export function require(ns: 'Nice', ver: '0.1'): typeof Nice01;
        export function require(ns: 'Notify', ver: '0.7'): typeof Notify07;
        export function require(ns: 'OSTree', ver: '1.0'): typeof OSTree10;
        export function require(ns: 'P11Kit', ver: '1.0'): typeof P11Kit10;
        export function require(ns: 'PackageKitGlib', ver: '1.0'): typeof PackageKitGlib10;
        export function require(ns: 'PackageKitPlugin', ver: '1.0'): typeof PackageKitPlugin10;
        export function require(ns: 'PanelApplet', ver: '4.0'): typeof PanelApplet40;
        export function require(ns: 'Pango', ver: '1.0'): typeof Pango10;
        export function require(ns: 'PangoCairo', ver: '1.0'): typeof PangoCairo10;
        export function require(ns: 'PangoFT2', ver: '1.0'): typeof PangoFT210;
        export function require(ns: 'PangoFc', ver: '1.0'): typeof PangoFc10;
        export function require(ns: 'PangoOT', ver: '1.0'): typeof PangoOT10;
        export function require(ns: 'PangoXft', ver: '1.0'): typeof PangoXft10;
        export function require(ns: 'Peas', ver: '1.0'): typeof Peas10;
        export function require(ns: 'PeasGtk', ver: '1.0'): typeof PeasGtk10;
        export function require(ns: 'Pnl', ver: '1.0'): typeof Pnl10;
        export function require(ns: 'Polkit', ver: '1.0'): typeof Polkit10;
        export function require(ns: 'PolkitAgent', ver: '1.0'): typeof PolkitAgent10;
        export function require(ns: 'Poppler', ver: '0.18'): typeof Poppler018;
        export function require(ns: 'Qmi', ver: '1.0'): typeof Qmi10;
        export function require(ns: 'Rest', ver: '0.7'): typeof Rest07;
        export function require(ns: 'RestExtras', ver: '0.7'): typeof RestExtras07;
        export function require(ns: 'Retro', ver: '0.14'): typeof Retro014;
        export function require(ns: 'Retro', ver: '1'): typeof Retro1;
        export function require(ns: 'Rsvg', ver: '2.0'): typeof Rsvg20;
        export function require(ns: 'RygelCore', ver: '2.4'): typeof RygelCore24;
        export function require(ns: 'RygelCore', ver: '2.6'): typeof RygelCore26;
        export function require(ns: 'RygelRenderer', ver: '2.4'): typeof RygelRenderer24;
        export function require(ns: 'RygelRenderer', ver: '2.6'): typeof RygelRenderer26;
        export function require(ns: 'RygelRendererGst', ver: '2.6'): typeof RygelRendererGst26;
        export function require(ns: 'RygelServer', ver: '2.4'): typeof RygelServer24;
        export function require(ns: 'RygelServer', ver: '2.6'): typeof RygelServer26;
        export function require(ns: 'Secret', ver: '1'): typeof Secret1;
        export function require(ns: 'SecretUnstable', ver: '0'): typeof SecretUnstable0;
        export function require(ns: 'Shumate', ver: '0.0'): typeof Shumate00;
        export function require(ns: 'Signon', ver: '2.0'): typeof Signon20;
        export function require(ns: 'Snapd', ver: '1'): typeof Snapd1;
        export function require(ns: 'Soup', ver: '2.4'): typeof Soup24;
        export function require(ns: 'SoupGNOME', ver: '2.4'): typeof SoupGNOME24;
        export function require(ns: 'SpiceClientGLib', ver: '2.0'): typeof SpiceClientGLib20;
        export function require(ns: 'SpiceClientGtk', ver: '3.0'): typeof SpiceClientGtk30;
        export function require(ns: 'Sushi', ver: '1.0'): typeof Sushi10;
        export function require(ns: 'TelepathyFarstream', ver: '0.6'): typeof TelepathyFarstream06;
        export function require(ns: 'TelepathyGLib', ver: '0.12'): typeof TelepathyGLib012;
        export function require(ns: 'TelepathyLogger', ver: '0.2'): typeof TelepathyLogger02;
        export function require(ns: 'Template', ver: '1.0'): typeof Template10;
        export function require(ns: 'Tepl', ver: '4'): typeof Tepl4;
        export function require(ns: 'Tepl', ver: '5'): typeof Tepl5;
        export function require(ns: 'Tepl', ver: '6'): typeof Tepl6;
        export function require(ns: 'TimezoneMap', ver: '1.0'): typeof TimezoneMap10;
        export function require(ns: 'Totem', ver: '1.0'): typeof Totem10;
        export function require(ns: 'TotemPlParser', ver: '1.0'): typeof TotemPlParser10;
        export function require(ns: 'Tracker', ver: '0.16'): typeof Tracker016;
        export function require(ns: 'Tracker', ver: '1.0'): typeof Tracker10;
        export function require(ns: 'Tracker', ver: '2.0'): typeof Tracker20;
        export function require(ns: 'Tracker', ver: '3.0'): typeof Tracker30;
        export function require(ns: 'TrackerControl', ver: '1.0'): typeof TrackerControl10;
        export function require(ns: 'TrackerControl', ver: '2.0'): typeof TrackerControl20;
        export function require(ns: 'TrackerExtract', ver: '0.16'): typeof TrackerExtract016;
        export function require(ns: 'TrackerMiner', ver: '0.16'): typeof TrackerMiner016;
        export function require(ns: 'TrackerMiner', ver: '1.0'): typeof TrackerMiner10;
        export function require(ns: 'TrackerMiner', ver: '2.0'): typeof TrackerMiner20;
        export function require(ns: 'UDisks', ver: '2.0'): typeof UDisks20;
        export function require(ns: 'UPowerGlib', ver: '1.0'): typeof UPowerGlib10;
        export function require(ns: 'Uhm', ver: '0.0'): typeof Uhm00;
        export function require(ns: 'Unique', ver: '3.0'): typeof Unique30;
        export function require(ns: 'Unity', ver: '6.0'): typeof Unity60;
        export function require(ns: 'Unity', ver: '7.0'): typeof Unity70;
        export function require(ns: 'UnityExtras', ver: '7.0'): typeof UnityExtras70;
        export function require(ns: 'Vda', ver: '1'): typeof Vda1;
        export function require(ns: 'Vgda', ver: '1'): typeof Vgda1;
        export function require(ns: 'Vgpg', ver: '1'): typeof Vgpg1;
        export function require(ns: 'Vgsl', ver: '1'): typeof Vgsl1;
        export function require(ns: 'Vpg', ver: '1'): typeof Vpg1;
        export function require(ns: 'Vte', ver: '2.91'): typeof Vte291;
        export function require(ns: 'Vulkan', ver: '1.0'): typeof Vulkan10;
        export function require(ns: 'WebKit', ver: '3.0'): typeof WebKit30;
        export function require(ns: 'WebKit2', ver: '3.0'): typeof WebKit230;
        export function require(ns: 'WebKit2', ver: '4.0'): typeof WebKit240;
        export function require(ns: 'WebKit2WebExtension', ver: '3.0'): typeof WebKit2WebExtension30;
        export function require(ns: 'WebKit2WebExtension', ver: '4.0'): typeof WebKit2WebExtension40;
        export function require(ns: 'Wnck', ver: '3.0'): typeof Wnck30;
        export function require(ns: 'Xkl', ver: '1.0'): typeof Xkl10;
        export function require(ns: 'Zeitgeist', ver: '2.0'): typeof Zeitgeist20;
        export function require(ns: 'Zpj', ver: '0.0'): typeof Zpj00;
        export function require(ns: 'cairo', ver: '1.0'): typeof Cairo10;
        export function require(ns: 'fontconfig', ver: '2.0'): typeof Fontconfig20;
        export function require(ns: 'freetype2', ver: '2.0'): typeof Freetype220;
        export function require(ns: 'gSignon', ver: '1.0'): typeof GSignon10;
        export function require(ns: 'libxml2', ver: '2.0'): typeof Libxml220;
        export function require(ns: 'win32', ver: '1.0'): typeof Win3210;
        export function require(ns: 'xfixes', ver: '4.0'): typeof Xfixes40;
        export function require(ns: 'xft', ver: '2.0'): typeof Xft20;
        export function require(ns: 'xlib', ver: '2.0'): typeof Xlib20;
        export function require(ns: 'xrandr', ver: '1.3'): typeof Xrandr13;
        export function require(ns: 'Gst', ver: '0.10'): typeof Gst010;
        export function require(ns: 'GstBase', ver: '0.10'): typeof GstBase010;
        export function require(ns: 'GstInterfaces', ver: '0.10'): typeof GstInterfaces010;
        export function require(ns: 'GstPbutils', ver: '0.10'): typeof GstPbutils010;
        export function require(ns: 'GstTag', ver: '0.10'): typeof GstTag010;
        export function require(ns: 'GstVideo', ver: '0.10'): typeof GstVideo010;
        export function require(ns: 'SocialWebClient', ver: '0.25'): typeof SocialWebClient025;
    export function startLoop(): void;
}
