# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        architecture:
          - x64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update package repository
      run: sudo apt-get update; # sudo apt-get upgrade
    - name: Install dependencies
      run: sudo apt-get --yes install gjs libappindicator3-dev libgda-5.0-dev libgirepository1.0-dev libgtk-3-dev libgtk-4-dev libgtksourceview-3.0-dev libnotify-dev libsoup2.4-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libadwaita-1-dev gnome-shell-common libmutter-14-dev libgcr-3-dev libgnome-desktop-4-dev build-essential gobject-introspection libgirepository1.0-dev libcairo2-dev
    - run: yarn --version
    - run: node --version
    - run: gjs --version
    - run: yarn install
    - run: yarn check
    - run: yarn build
    - run: yarn build:types
    - name: Show diff
      run: (cd ./types && git diff | cat)
    - run: yarn check:types
    - run: yarn test:unit
    - run: yarn build:examples
    - run: yarn check:examples
    - run: yarn test:examples:cli